apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
  namespace: blue-green-webapp
  labels:
    app: backend
    environment: green
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      environment: green
  template:
    metadata:
      labels:
        app: backend
        environment: green
        component: backend
        version: v1.1.0
    spec:
      containers:
        - name: backend
          image: backend:v1.1.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ENVIRONMENT
              value: "green"
            - name: VERSION
              value: "v1.1.0"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          envFrom:
            - configMapRef:
                name: app-config
          resources:
            requests:
              memory: '128Mi'
              cpu: '100m'
            limits:
              memory: '256Mi'
              cpu: '200m'
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3